### ISSUE TITLE
can't override ConfigCatClient via webmock (bypassing via cache?)

### ISSUE THREAD

**Issue by graial** [configcat/ruby-sdk#17]
### Describe the bug

Can't seem to override config in testing my rails app.  I have webmock set-up to mock external HTTP calls and I did need to mock the configcat request to get my tests running initially.

### To reproduce

As per suggestion in docs, I created a Singleton via an initializer:

```
# config/initializers/configcat.rb
require 'configcat'
require 'singleton'

class FeatureFlagConfig
  include Singleton
  def initialize
    @client = ConfigCat.create_client(ENV["CONFIGCAT_KEY"])
  end

  def get_value(flag)
  	@client.get_value(flag, false)
  end

  def refresh
    @client.force_refresh
  end
end
```
i create a stub as per webmock
```
require 'webmock'
include WebMock::API

def stub_configcat_config
	stub_request(
		:get, 
		"https://cdn-global.configcat.com/configuration-files/#{ENV['CONFIGCAT_KEY']}/config_v5.json"
	).to_return(
		status: 200,
		body: {
		  "f": {
		    "my_feature": {
		      "v": false,
		    }
		  }
		}.to_json
	)
end
```
within my `rails_helper.rb`, I add a before hook

```
  config.before(:each, type: :request) do
    WebMock.disable_net_connect!(allow: '127.0.0.1')
    stub_configcat_config
    FeatureFlagConfig.instance.refresh
puts FeatureFlagConfig.instance.get_value('my_feature')
  end

```

If i now run 15 or 20 specs, while it's running, toggle the feature flag.  It will show the returned value change from `true` to `false` (or V.V.) during the run.

### Expected behavior

I expected the value I provided in my http mock_request to pverride the result.  I guess somehow the caching is bypassing webmock.  I anticipate this would cause problems in CI.  I also want to avoid using a different Client / caching strategy for the test environment

### Screenshots

> bundle exec rspec spec/requests/
> {"my_feature"=>false}
> .{"my_feature"=>false}
> .{"my_feature"=>false}
> .{"my_feature"=>false}
> .{"my_feature"=>false}
> .{"my_feature"=>false}
> .{"my_feature"=>false}
> .*{"my_feature"=>true}
> F{"my_feature"=>true}
> .{"my_feature"=>true}
> .{"my_feature"=>true}
> F{"my_feature"=>true}
> .**{"my_feature"=>true}
> F{"my_feature"=>true}
> .{"my_feature"=>true}

**Comment by graial** [comment]
A bit of extra info, when the tests run in a fresh docker image (with webmock enabled), I get the following 

` WARN -- : Evaluating get_value('my_feature') failed. Cache is empty. Returning default_value in your get_value call: [false]. `

So in addition to being bypassed, the webmock stub fails to provide the configuration in the test-suite when there is no cache already present.

**Comment by kp-cat** [comment]
Hi @graial,

Thanks for reaching out.
I couldn't reproduce the issue.

Could you please tell me which ConfigCat SDK version you are using?
Could you please provide a full example (e.g. on github)? That would be a big help to repro the issue.

**Comment by graial** [comment]
I've produced a minimal example here but the behaviour isn't seen:
https://github.com/graial/configcat_stubbed_spec_example

I assume it is v5 (based on the filename from the stub).
in Gemfile.lock, it says     configcat (5.0.2)

So it appears to be a bug in my initial implementation. I'll poke around a little more and circle back

**Comment by graial** [comment]
> Hi @graial,
> 
> Thanks for reaching out. I couldn't reproduce the issue.
> 
> Could you please tell me which ConfigCat SDK version you are using? Could you please provide a full example (e.g. on github)? That would be a big help to repro the issue.

Are you able to point me to where the update call is made within the SDK?

I am still unable to locate the issue in my main app and Webmock is failing to block the update call to the api no matter where I place `WebMock.disable_net_connect!` within the spec or `rails_helper.rb` folder.

I also tried a fresh clone of the repo on a different computer so it's not a local caching issue

**Comment by kp-cat** [comment]
Hi @graial,

We download the config.json in the `ConfigFetcher` class :
https://github.com/configcat/ruby-sdk/blob/master/lib/configcat/configfetcher.rb#L172

The caching/fechtime checking in the `ConfigService` class:  
https://github.com/configcat/ruby-sdk/blob/master/lib/configcat/configservice.rb

We have just releases a new SDK version `6.0.0`.
In this version we restructured the config fetching. I think it worth to check the issue with this release.

**Comment by kp-cat** [comment]
I also checked your minimal example project. I didn't get the issue either.
